# vibeCop - Automated Code Analysis
#
# This workflow runs vibeCop static analysis on a schedule and creates
# GitHub issues for findings that AI coding agents can fix.
#
# ┌─────────────────────────────────────────────────────────────────┐
# │  QUICK START                                                     │
# │                                                                  │
# │  1. Copy this file to: .github/workflows/vibecop.yml            │
# │  2. Replace <OWNER> with the vibeCop repo owner (e.g., WolffM)  │
# │  3. Commit and push - analysis runs automatically!              │
# │                                                                  │
# │  Optional: Add vibecop.yml to customize tool settings           │
# └─────────────────────────────────────────────────────────────────┘
#
# Tools included:
#   - Trunk (ESLint, Prettier, yamllint, markdownlint, osv-scanner, etc.)
#   - TypeScript compiler (tsc)
#   - jscpd (duplicate code detection)
#   - dependency-cruiser (architecture/circular deps)
#   - knip (unused exports/dependencies)
#   - Semgrep (security scanning)

name: vibeCop Analysis

on:
  # ═══════════════════════════════════════════════════════════════
  # SCHEDULE - Choose your cadence by uncommenting ONE cron line
  # ═══════════════════════════════════════════════════════════════
  schedule:
    # Weekly (recommended) - Mondays at 03:17 UTC
    - cron: "17 3 * * 1"

    # Daily - uncomment for active development
    # - cron: '17 3 * * *'

    # Monthly - uncomment for stable projects
    # - cron: '17 3 1 * *'

  # Manual trigger with options
  workflow_dispatch:
    inputs:
      cadence:
        description: "Analysis depth"
        required: false
        default: "weekly"
        type: choice
        options:
          - daily
          - weekly
          - monthly
      severity_threshold:
        description: "Minimum severity for issues"
        required: false
        default: "info"
        type: choice
        options:
          - critical
          - high
          - medium
          - low
          - info
      merge_strategy:
        description: "How to group findings into issues"
        required: false
        default: "same-rule"
        type: choice
        options:
          - none
          - same-file
          - same-rule
          - same-tool

jobs:
  analyze:
    # ═══════════════════════════════════════════════════════════════
    # REQUIRED: Replace <OWNER> with the GitHub user/org hosting vibeCop
    # Example: WolffM/vibeCop/.github/workflows/reusable-analyze.yml@main
    # ═══════════════════════════════════════════════════════════════
    uses: <OWNER>/vibeCop/.github/workflows/reusable-analyze.yml@main

    with:
      # ─────────────────────────────────────────────────────────────
      # Cadence: Determines which tools run
      #   daily   - Fast checks only (Trunk, tsc)
      #   weekly  - + jscpd, dependency-cruiser
      #   monthly - + knip, semgrep (full scan)
      # ─────────────────────────────────────────────────────────────
      cadence: ${{ inputs.cadence || 'weekly' }}

      # ─────────────────────────────────────────────────────────────
      # Issue Filtering
      # ─────────────────────────────────────────────────────────────
      # Minimum severity: critical | high | medium | low | info
      severity_threshold: ${{ inputs.severity_threshold || 'info' }}

      # Minimum confidence: high | medium | low
      confidence_threshold: "low"

      # ─────────────────────────────────────────────────────────────
      # Issue Merging - Reduce noise by grouping related findings
      #   none      - One issue per finding (most granular)
      #   same-file - Group by tool + rule + file
      #   same-rule - Group by tool + rule across all files (recommended)
      #   same-tool - One issue per tool (most compact)
      # ─────────────────────────────────────────────────────────────
      merge_strategy: ${{ inputs.merge_strategy || 'same-rule' }}

      # ─────────────────────────────────────────────────────────────
      # Optional Settings
      # ─────────────────────────────────────────────────────────────
      # Label applied to all created issues
      issue_label: "vibeCop"

      # Path to repo-specific config file (optional)
      # config_path: 'vibecop.yml'

      # Skip issue creation (just run analysis)
      # skip_issues: false

      # Enable full scan regardless of cadence
      # deep_scan: false

    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
