# vibeCop Caller Workflow Template
#
# Copy this file to your repository at .github/workflows/vibecop.yml
# and customize the settings below.
#
# Replace <OWNER> with your GitHub organization or username.
#
# Note: Daily runs automatically skip if no commits in the last 25 hours,
# saving CI minutes on unchanged code.

name: vibeCop (Scheduled)

on:
  # Scheduled analysis
  schedule:
    # Weekly: Mondays at 03:17 UTC
    - cron: '17 3 * * 1'

    # Uncomment for daily runs:
    # - cron: '17 3 * * *'

    # Uncomment for monthly runs (1st of month):
    # - cron: '17 3 1 * *'

  # Allow manual triggers
  workflow_dispatch:
    inputs:
      cadence:
        description: 'Analysis cadence'
        required: false
        default: 'weekly'
        type: choice
        options:
          - daily
          - weekly
          - monthly

jobs:
  vibeCop:
    uses: <OWNER>/vibeCop/.github/workflows/reusable-analyze.yml@main
    with:
      # Match cadence to your schedule (daily/weekly/monthly)
      cadence: ${{ inputs.cadence || 'weekly' }}

      # Trunk check arguments
      trunk_arguments: 'check'

      # Label for created issues
      issue_label: 'vibeCop'

      # Path to repo-specific config (optional)
      config_path: 'vibecop.yml'

    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

# Optional: Add PR workflow for diff-only checks
# Uncomment and adjust as needed:
#
# pr-check:
#   if: github.event_name == 'pull_request'
#   uses: <OWNER>/vibeCop/.github/workflows/reusable-pr-review.yml@main
#   with:
#     trunk_arguments: 'check'
#   secrets:
#     GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
