# vibeCop Analysis Workflow
#
# This workflow runs vibeCop static analysis on your repository.
# Copy this file to .github/workflows/vibecop.yml in your repository.
#
# For more info: https://github.com/WolffM/vibecop

name: vibeCop Analysis

on:
  # Run weekly on Monday at 3am UTC
  schedule:
    - cron: "0 3 * * 1"

  # Run on push to main (daily cadence)
  push:
    branches: [main, master]

  # Allow manual trigger
  workflow_dispatch:
    inputs:
      cadence:
        description: "Analysis cadence"
        required: false
        default: "weekly"
        type: choice
        options:
          - daily
          - weekly
          - monthly
      skip_issues:
        description: "Skip issue creation (dry run)"
        required: false
        default: false
        type: boolean

permissions:
  contents: read
  issues: write
  security-events: write

jobs:
  analyze:
    name: Static Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run vibeCop
        uses: WolffM/vibecop@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          cadence: ${{ github.event.inputs.cadence || 'weekly' }}
          severity_threshold: "low"
          confidence_threshold: "medium"
          merge_strategy: "same-linter"
          skip_issues: ${{ github.event.inputs.skip_issues || 'false' }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: vibecop-results
          path: .vibecop-output/
          retention-days: 14
